language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest --cov-report term-missing --cov=Api
after_success:
  - coveralls

cache:
  pip


#script:  - python -m pytest --cov-report term-missing --cov=resources
#notifications:  email: false